UPDATE_TIMESTEP = 0.035


MAX_RECOIL = 5
LONG_RECOIL = 2
MED_RECOIL = 1
SHORT_RECOIL = 0.5
SHORTER_RECOIL = 0.25
MIN_RECOIL = 0.1
DEATH_INTERVAL = 3
COUNTER_MAX = 10
DASH_RECOIL_MULTI = 1.25
ACTION_TIME_DEFAULT = 3
RECOIL_MULTI = COUNTER_MULTI = 1 
LVUP_MULTI = 1000
GAME_SPEED = 1
REDRAW_MULTI = 10
DIRECTIONS = ("up", "down", "left", "right")
SLOW_RECOVERY_MULTI = 0.5
MOD_WEIGHT = 0.1

EXP_PER_LEVEL = 1000
EXP_PER_KILL = 100
BASE_MOVEMENT_SPEED = 2.75

HEALTH_BARS_LENGTH = RECOIL_BARS_LENGTH = 15

INVENTORY_SIZE = 12
EXTRA_ENCUMBRANCE_MULTI = 2




###DEFAULT KEY MAP
KEY_MAP = {
	"inventory-menu" : "ctrl a", 
	"status-menu" : "ctrl s",
	"help-menu" : "ctrl d"
}