MAX_RECOIL = 50
LONG_RECOIL = 20
MED_RECOIL = 10
SHORT_RECOIL = 3
ACTION_TIME_DEFAULT = 5
RECOIL_MULTI = COUNTER_MULTI = 15 
LVUP_MULTI = 1000
GAME_SPEED = 1
DIRECTIONS = ("up", "down", "left", "right")