UPDATE_TIMESTEP = 0.025
MAX_RECOIL = 5
LONG_RECOIL = 2
MED_RECOIL = 1
SHORT_RECOIL = 0.5
SHORTER_RECOIL = 0.25
MIN_RECOIL = 0.1
DEATH_INTERVAL = 5
COUNTER_MAX = 10
DASH_RECOIL_MULTI = 1.25
ACTION_TIME_DEFAULT = 3
RECOIL_MULTI = COUNTER_MULTI = 1 
LVUP_MULTI = 1000
GAME_SPEED = 1
REDRAW_MULTI = 10
DIRECTIONS = ("up", "down", "left", "right")
SLOW_RECOVERY_MULTI = 0.5
MOD_WEIGHT = 0.1